#!/bin/bash
#SBATCH --job-name=unet
#SBATCH --partition=workq
#SBATCH --account=ric.medicinanucleare
#SBATCH --time=24:00:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user=mongardi.sofia@hsr.it
#SBATCH --error="/beegfs/scratch/ric.medicinanucleare/mongardi.sofia/Thesis/Thesis/sbatch_job/unet.err"
#SBATCH --output="/beegfs/scratch/ric.medicinanucleare/mongardi.sofia/Thesis/Thesis/sbatch_job/unet.out"

python3 scripts_2/main_2.py --data_dir data/new_nrrd --txt_dir data/images.txt  --results_dir results/train_results_adam_0.0003_eps/  --loss dice --augmentation False  --shuffle --lr_adam 0.0003 --epochs 1200 --eps 1e-3 --model models.Unet_R2
python3 scripts_2/test_main_2.py --data_dir data/new_nrrd --txt_dir data/images.txt  --results_dir results/train_results_adam_0.0003_eps/  --loss dice --augmentation False  --shuffle --eps 1e-3  --model models.Unet_R2
