#!/bin/bash
#SBATCH --job-name=unet
#SBATCH --partition=workq
#SBATCH --account=ric.medicinanucleare
#SBATCH --time=24:00:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user=mongardi.sofia@hsr.it
#SBATCH --error="/beegfs/scratch/ric.medicinanucleare/mongardi.sofia/Thesis/Thesis/sbatch_job/unet.err"
#SBATCH --output="/beegfs/scratch/ric.medicinanucleare/mongardi.sofia/Thesis/Thesis/sbatch_job/unet.out"


python3 scripts/Test.py --data_dir data/Images_cnn --txt_dir data/images.txt  --results_dir results/train_results_adam_0.0005_bs4/  --loss dice --augmentation False  --shuffle --lr_adam 0.0005 --epochs 150 --eps 1e-3 --model models.Unet --batch_size 4 --batchnorm True


python3 scripts/Test.py --data_dir data/Images_cnn --txt_dir data/images.txt  --results_dir results/train_results_adam_0.0003_bs4/  --loss dice --augmentation False  --shuffle --lr_adam 0.0003 --epochs 150 --eps 1e-3 --model models.Unet --batch_size 4 --batchnorm True


python3 scripts/Test.py --data_dir data/Images_cnn --txt_dir data/images.txt  --results_dir results/train_results_adam_0.0001_bs4/  --loss dice --augmentation False  --shuffle --lr_adam 0.0001 --epochs 150 --eps 1e-3 --model models.Unet --batch_size 4 --batchnorm True



python3 scripts/Test.py --data_dir data/Images_cnn --txt_dir data/images.txt  --results_dir results/train_results_adam_0.0005_bs2/  --loss dice --augmentation False  --shuffle --lr_adam 0.0005 --epochs 150 --eps 1e-3 --model models.Unet --batch_size 2 --batchnorm True
python3 scripts/Test.py --data_dir data/Images_cnn --txt_dir data/images.txt  --results_dir results/train_results_adam_0.0003_bs2/  --loss dice --augmentation False  --shuffle --lr_adam 0.0003 --epochs 150 --eps 1e-3 --model models.Unet --batch_size 2 --batchnorm True

python3 scripts/Test.py --data_dir data/Images_cnn --txt_dir data/images.txt  --results_dir results/train_results_adam_0.0001_bs2/  --loss dice --augmentation False  --shuffle --lr_adam 0.0001 --epochs 150 --eps 1e-3 --model models.Unet --batch_size 2 --batchnorm True
